spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sopt
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rj7783208232
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: false